# Generated by Django 4.0.2 on 2022-03-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torts', '0002_offer_problem_statusforoffer_statusforproblem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='tort',
            options={'ordering': ['name'], 'verbose_name': 'Торт', 'verbose_name_plural': 'Торты'},
        ),
    ]
