# Generated by Django 4.0.2 on 2022-03-10 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torts', '0003_alter_category_options_alter_tort_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torts.statusforoffer', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='offer',
            name='tort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torts.tort', verbose_name='Заказанный торт'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_photo',
            field=models.ImageField(blank=True, upload_to='photos/problem_photos/%Y/%m%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torts.statusforproblem', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torts.tort', verbose_name='Заказанный торт'),
        ),
        migrations.AddField(
            model_name='tort',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='torts.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='tort',
            name='tort_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tort',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tort',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tort',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
