# Generated by Django 4.0.2 on 2022-03-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torts', '0004_offer_status_offer_tort_problem_problem_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/category_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torts.statusforoffer', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='tort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torts.tort', verbose_name='Заказанный торт'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torts.statusforproblem', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='torts.tort', verbose_name='Заказанный торт'),
        ),
    ]
