# Generated by Django 4.0.2 on 2022-04-03 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torts', '0005_category_photo_alter_offer_status_alter_offer_tort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tort',
            name='tort_photo',
        ),
        migrations.CreateModel(
            name='TortPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tort_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m%d/', verbose_name='Фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='torts.tort')),
            ],
        ),
    ]
