# Generated by Django 4.0.2 on 2022-04-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torts', '0006_remove_tort_tort_photo_tortphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tort',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='photos/maintort_photos/', verbose_name='Фото'),
        ),
    ]
